### ISSUE TITLE
Difference between 'joints' and 'volume_joints' from hand_pose_predictor

### ISSUE THREAD

**Issue by dqj5182** [zerchen/gSDF#13]
I have a question regarding the outputs of hand_pose_predictor.
The hand_pose_predictor has various outputs, but one I find different from other hand pose predictors was 'volume_joints'.
To me, it seemed that 'joints' are prediction of MANO joints, directly extracted from predicted MANO hand mesh. And, the 'volume_joints' seemed to be the prediction of hand joints directly from predicted heatmaps of the hand joints. Is this correct?

**Comment by zerchen** [comment]
Yes, that's correct!
