### ISSUE TITLE
Implementation on HO3D dataset

### ISSUE THREAD

**Issue by Duckkkkky** [zerchen/gSDF#18]
Hello Zerui, first of all, thanks for the amazing work!
I have found that the baseline can also be tested on HO3Dv3 dataset mentioned in ./playground/.../recon.py, but I have no idea how to implement it.(for example, how to generate config files like obman_test.json, and how to modify obman.py to something like ho3dv3.py...?) It would be appreciated if you'd like to share some tips on it.

**Comment by zerchen** [comment]
Hi,

Sorry for a late reply. To make the code work on HO3D, I think what you mainly need to do is to convert the annotation into a COCO-style json file (you could use [this](https://github.com/zerchen/gSDF/blob/master/preprocess/cocoify_obman.py) for a reference). Then, you can write ho3dv3.py in a similar style as obman.py.

Best,
Zerui

**Comment by Duckkkkky** [comment]
> Hi,
> 
> Sorry for a late reply. To make the code work on HO3D, I think what you mainly need to do is to convert the annotation into a COCO-style json file (you could use [this](https://github.com/zerchen/gSDF/blob/master/preprocess/cocoify_obman.py) for a reference). Then, you can write ho3dv3.py in a similar style as obman.py.
> 
> Best, Zerui

Thanks a lot for your reply! :)
In fact, during last two weeks, I have worked out the testing procedure on HO3Dv3 and the test program is executable.(Modified it refer to the preprocess code using in dexycb dataset in this repository, and used the pre-trained model also on dexycb to test) However, while I could work out on dexycb dataset and obtain nice results, the reconstructed mesh from HO3Dv3 seems bad and I couldn't get a hand-like mesh. Is it because the pose-kpt need to train again on a new dataset or perhaps it means that I didn't preprocess the dataset correctly...? 
I have tried to compute the bounding box and crop the original image size to 256x256, and also changed the intrinsic matrix of camera. 
Wish you have a great day!

**Comment by zerchen** [comment]
I think it is reasonable that you didn't get good results on HO3Dv3. To figure out the reasons, you could test/visualize the trained keypoint estimator on HO3Dv3 images. Maybe you also need to check whether the [sdf_scale](https://github.com/zerchen/gSDF/blob/05101b5bde6765e9168026cff853b74a1412c125/datasets/dexycb/dexycb.py#L121C17-L121C83), sdf_offset(https://github.com/zerchen/gSDF/blob/05101b5bde6765e9168026cff853b74a1412c125/datasets/dexycb/dexycb.py#L122) are correctly set, which vary between different datasets and are crucial for the performance. I think another important thing is that the domain gap (i.e., image apperance) between dexycb and ho3d is large, which result in poor performance when you try to generalize the dexycb trained model to other datasets.

**Comment by Duckkkkky** [comment]
Thank you for your detailed explanation! I'll try to work it out.
