### ISSUE TITLE
Creation of the sdf files

### ISSUE THREAD

**Issue by wetoo-cando** [zerchen/gSDF#5]
@zerchen nice work!
You provide the sdf files for download. How were these files created?

**Comment by zerchen** [comment]
Thanks for your interests. These files are generated by [codes](https://github.com/zerchen/AlignSDF/tree/master/scripts/sample_points) provided in my old repo. You could find prep_obman.py and prep_dexycb.py to generate sdf files.

**Comment by wetoo-cando** [comment]
Thanks @zerchen !
