### ISSUE TITLE
How to create my own sdf data

### ISSUE THREAD

**Issue by jeffsonyu** [zerchen/gSDF#7]
Hello! Thanks for the great work! I'm now implementing another dataset for training, and have got some trouble making the sdf data. Could you tell me how you created the SDF data for obman and dexycb datasets? Thank you again!

**Comment by jeffsonyu** [comment]
I've seen the same issue which solved my problem. Sorry for the duplication.

**Comment by TheVirtuoso7** [comment]
> I've seen the same issue which solved my problem. Sorry for the duplication.我遇到了同样的问题，这解决了我的问题。抱歉重复了。
Hi there! I hope you’re doing well. Would you happen to have the full SDF file for Dexycb? If so, I would really appreciate it if you could share it. Thank you!
